Rename `Velocidi` references to `Kevel`
adzerk/apso pull request #554
Opened 2023-10-09 17:43 UTC by xRuiAlves

Just renaming the public-facing documentation text references.

We should probably eventually also rename the package names from `velocidi` to `kevel`.

### Does this change relate to existing issues or pull requests?

Closes https://github.com/adzerk/apso/issues/553.

### Does this change require an update to the documentation?

This is an updated to the documentation!

### How has this been tested?

Tested hyperlinks to GitHub badges / hosted images after the `velocidi` -> `adzerk` organization update.

2023-10-09 21:00 UTC, jcazevedo requested changes

2023-10-10 08:16 UTC, xRuiAlves commented on README.md
> +# Apso [![Build Status](https://github.com/adzerk/apso/workflows/CI/badge.svg?branch=master)](https://github.com/adzerk/apso/actions?query=workflow%3ACI+branch%3Amaster) [![Maven Central](https://img
Oops, I could swear this badge works! But honestly, didn't think too much about it - Sorry about that.

2023-10-10 08:17 UTC, xRuiAlves commented on docs/README.md
> +# Apso [![Build Status](https://github.com/adzerk/apso/workflows/CI/badge.svg?branch=master)](https://github.com/adzerk/apso/actions?query=workflow%3ACI+branch%3Amaster) [![Maven Central](https://img
Oops, I could swear this badge works! But honestly, didn't think too much about it - Sorry about that.

2023-10-10 08:19 UTC, jcazevedo approved these changes

2023-10-10 08:24 UTC, merged