Rename packages organization from `com.velocidi` to `com.kevel`
adzerk/apso pull request #745
Opened 2024-10-12 11:21 UTC by beatriz

This changes the packages from the `com.velocidi` to `com.kevel` organization to ... the organizational change. For now, it doesn't touch the publishing organization as I still need to figure out some things for that.
After making the change I wondered if we'd want to use `adzerk` instead to be consistent with the GitHub organization name, what do you think?

### Does this change relate to existing issues or pull requests?

No.

### Does this change require an update to the documentation?

Updated the `README` docs as well.

### How has this been tested?

Relying on CI to validate everything keeps working.

2024-10-14 16:56 UTC, jcazevedo commented
> After making the change I wondered if we'd want to use `adzerk` instead to be consistent with the GitHub organization name, what do you think?

I'd rather not move from one old name (`com.velocidi`) to another old one (`com.adzerk`).

2024-10-14 17:17 UTC, jcazevedo requested changes
Thanks for getting the ball rolling on this!

Can we also rename the `**/com/velocidi/*` folders to `**/com/kevel/*`?

2024-10-14 17:17 UTC, jcazevedo commented on hashing/src/main/java/com/velocidi/apso/hashing/MurmurHash3.java
> +package com.kevel.apso.hashing;
Can we rollback the other changes in this file? I suspect some unwanted IDE shenanigans went unnoticed here.

2024-10-15 09:50 UTC, beatriz commented
> Can we also rename the `**/com/velocidi/*` folders to `**/com/kevel/*`?

Yeah, totally missed that 😅 Done!

2024-10-16 13:24 UTC, jcazevedo approved these changes
Thank you!

2024-10-16 15:46 UTC, merged